services:
  # FastAPI Development Server
  casnet-api:
    build:
      context: .
      target: development
    container_name: casnet-backend-dev
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DATA_COUNT=10
      - ENABLE_DETAILED_LOGGING=true
      - SECRET_KEY=dev_secret_key_change_in_production
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173,http://localhost:8080,http://localhost:4200
    volumes:
      # Mount source code for hot reload in development
      - ./src:/app/src
      # Persist SQLite database
      - sqlite_data:/app/data
    restart: unless-stopped
    networks:
      - casnet-network
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  # SQLite database persistence
  sqlite_data:
    driver: local

networks:
  casnet-network:
    driver: bridge
